index.html
=> test...infinite

src/App.tsx, src/components/landing/LoadingRedirect.tsx, src/components/landing/index.ts, src/utils/browserDetect.ts
=> 🐛 Fix: 인앱브라우저로 열리면 외부로 리다이렉트

src/utils/browserDetect.ts
=> 🔧 Wrench: 대체 코드 추가

src/utils/browserDetect.ts
=> ios 기본 브라우저 코드 변경

src/utils/browserDetect.ts
=> 제발 사파리...제발

src/components/landing/LoadingRedirect.tsx
=> btn style 수정

src/components/landing/LoadingRedirect.tsx, src/utils/browserDetect.ts
=> ios 보안관련 처리

src/components/landing/LoadingRedirect.tsx, src/utils/browserDetect.ts
=> style 수정, 리다이렉트 수정

src/utils/browserDetect.ts
=> naver 처리 추가

src/components/my/FcmToggle/FcmToggle.tsx, src/hooks/useLanding.ts, src/hooks/useNotification.ts
=> ✨ Feat: 알림 관련 TEST 2

src/hooks/useLanding.ts, src/hooks/useNotification.ts
=> ✨ Feat: 알림 테스트 3

src/components/my/FcmToggle/FcmToggle.tsx, src/hooks/useNotification.ts
=> ✨ Feat: 알림 TEST 4

src/components/my/AccountSetBtn/AccountSetBtn.tsx, src/hooks/useAccountManage.ts, src/hooks/useLeave.ts, src/pages/group/GroupSelectPage.tsx, src/router.tsx
> 그룹 목록 페이지에 설정 버튼 추가
> fork 떠온 레포 #157
- router 수정
- 버튼 추가
- 경로 수정
>
=> Feature/#157 - 그룹 목록 페이지에 설정 버튼 추가

src/utils/dateUtils.ts
> date 5주차 이후 처리문 추가
> #172
- date 5주차 이후 처리문 추가
>
=> 🐛 Fix: date 5주차 이후 처리문 추가

public/firebase-messaging-sw.js
=> ✨ Update: Clean up whitespace in firebase-messaging-sw.js

src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
=> 🔧 Wrench: log 확인 테스트 코드

src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
=> 🔧 Wrench: monthKey 로그 추가

src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx, src/hooks/useMonthlyStatistics.ts
=> 🔧 Wrench: 월 변경 시 monthKey 전달 및 불필요한 코드 제거

src/hooks/useMonthlyStatistics.ts
=> 🔧 Wrench: 불필요한 로그 제거

src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItem.tsx, src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.tsx, src/components/housework/ManagerSelectSheet/ManagerSelectSheet.tsx
=> ✨ Feat: ai 자동 선택 스크롤기능 추가

src/pages/statistics/WeeklyStatisticsPage.tsx
=> 🔧 Wrench: 주간 통계 페이지에 로그 추가

src/hooks/useWeeklyStatistics.ts
=> 🔧 Wrench: 주간 통계 랭킹 데이터 조회 성공 로그 삭제

src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
=> 💄 Style: HouseWorkSheet 컴포넌트의 레이아웃 수정

src/components/common/search/SearchInput.tsx
=> 💄 Style: SearchInput 컴포넌트의 패딩 수정

src/components/common/search/SearchInput.tsx
=> 💄 Style: SearchInput 컴포넌트의 취소 버튼 패딩 추가

src/components/common/search/SearchInput.tsx, src/components/common/tab/PresetTab/PresetTab.tsx, src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx, src/pages/group/PresetSettingPage.tsx
=> ✨ Feat: SearchInput 컴포넌트에 handleChange 프로퍼티 추가 및 검색 기능 구현

src/components/common/tab/PresetTab/PresetTab.tsx, src/pages/group/PresetSettingPage.tsx
=> ✨ Feat: PresetTab에 searchQuery 프로퍼티 추가하여 검색 기능 연동

src/components/common/tab/PresetTab/PresetTab.tsx
=> 💄 Style: PresetTab 컴포넌트의 레이아웃 수정 및 flex 속성 조정

src/components/common/tab/PresetTab/PresetTab.tsx
=> 💄 Style: PresetTab 컴포넌트의 레이아웃 수정 및 사용자 정의 메시지 포맷 개선

src/components/common/tab/PresetTab/PresetTab.tsx
=> 💄 Style: PresetTab 컴포넌트의 하단 여백 조정

src/pages/group/PresetSettingPage.tsx
=> 💄 Style: PresetSettingPage 컴포넌트의 상단 div에 flex 및 gap 클래스 추가

src/hooks/useWeeklyStatistics.ts, src/services/statistics/getWeeklyScore.ts
=> Fix/#180 - 주간 통계 점검

src/services/statistics/getWeeklyScore.ts
=> 🔧 Wrench: log 삭제

public/.well-known/assetlinks.json
> assetlinks.json 파일 추가
> #189
assetlinks.json 파일 추가
>
=> ➕ Add: assetlinks.json 파일 추가
